package interfaces;

import javax.swing.SpinnerNumberModel;

public class UsandoComponente extends javax.swing.JFrame {

    /**
     * Creates new form UsandoComponente
     */
    public UsandoComponente() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainContainer = new javax.swing.JPanel();
        panelCrearAlarma = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        horaAlarma = new javax.swing.JSpinner(new SpinnerNumberModel(0, 0, 23, 1));
        jLabel2 = new javax.swing.JLabel();
        minutoAlarma = new javax.swing.JSpinner(new SpinnerNumberModel(0, 0, 59, 1));
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        componenteRelojBeans3 = new components.ComponenteRelojBeans();
        switchFormatTime = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainContainer.setBackground(new java.awt.Color(255, 255, 255));
        mainContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelCrearAlarma.setBackground(new java.awt.Color(255, 255, 255));
        panelCrearAlarma.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelCrearAlarma.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Hora");
        panelCrearAlarma.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 63, -1));
        panelCrearAlarma.add(horaAlarma, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel2.setText("Minuto");
        panelCrearAlarma.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 60, -1));
        panelCrearAlarma.add(minutoAlarma, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Crear alarma");
        panelCrearAlarma.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 160, -1));

        jButton1.setText("Añadir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelCrearAlarma.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 100, -1));

        mainContainer.add(panelCrearAlarma, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 260, 120));

        componenteRelojBeans3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        componenteRelojBeans3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        componenteRelojBeans3.setHourAlarm(13);
        componenteRelojBeans3.setMinutesAlarm(31);
        mainContainer.add(componenteRelojBeans3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 400, 30));

        switchFormatTime.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        switchFormatTime.setText("Formato 24h");
        switchFormatTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchFormatTimeActionPerformed(evt);
            }
        });
        mainContainer.add(switchFormatTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 6, 141, 36));

        getContentPane().add(mainContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int hora = (Integer) horaAlarma.getValue();
        int minuto = (Integer) minutoAlarma.getValue();
        if(hora >= 0 && hora <= 23 && minuto >= 0 && minuto <= 59){
            System.out.println("Alarma creada");
            componenteRelojBeans3.setEnableAlarm(true);
            componenteRelojBeans3.setHourAlarm(hora);
            componenteRelojBeans3.setMinutesAlarm(minuto);
        }else{
            System.out.println("El formato de hora introducido no es válido");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void switchFormatTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchFormatTimeActionPerformed
        componenteRelojBeans3.setFormato24h(!componenteRelojBeans3.isFormato24h());
    }//GEN-LAST:event_switchFormatTimeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsandoComponente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsandoComponente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsandoComponente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsandoComponente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsandoComponente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private components.ComponenteRelojBeans componenteRelojBeans3;
    private javax.swing.JSpinner horaAlarma;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel mainContainer;
    private javax.swing.JSpinner minutoAlarma;
    private javax.swing.JPanel panelCrearAlarma;
    private javax.swing.JRadioButton switchFormatTime;
    // End of variables declaration//GEN-END:variables
}
